name: Assign Reviewers from CODEOWNERS

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  assign:
    permissions:
      pull_requests: write # Explicitly grant write permission

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign reviewers based on CODEOWNERS
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              const response = await github.rest.pulls.requestReviewers({
                owner: owner,
                repo: repo,
                pull_number: prNumber,
              });

              console.log("API Response:", JSON.stringify(response.data, null, 2)); // Log formatted JSON
              console.log(`Reviewers requested for PR #${prNumber}`);

            } catch (error) {
              console.error("API Error:", error); // Log the full error object
              if (error.response) {
                console.error("API Error Response:", JSON.stringify(error.response.data, null, 2)); // Log detailed error
              }
            }
